plugins {
    id 'java'
}

group = 'hello'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc:4.1.1'
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test:4.1.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.3'
}

tasks.named('test') {
    useJUnitPlatform()
}
