spring.application.name=exception
spring.web.error.whitelabel.enabled=false
# 아래 내용들은 클라이언트측으로 노출 안 하는 게 맞다 (API 응답도 마찬가지)
spring.web.error.include-exception=true
spring.web.error.include-message=always
spring.web.error.include-stacktrace=on_param
spring.web.error.include-binding-errors=on_param