spring:
  application:
    name: spring-adv1
#  aop:
#    proxy-target-class: false # jdk proxy
  main:
    allow-circular-references: true


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: TRACE
