spring:
  application:
    name: spring-adv1
#  aop:
#    proxy-target-class: false # jdk proxy

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: TRACE
