plugins {
    id 'java'
    id 'war'
}

group = 'org'
version = '0.0.1-SNAPSHOT'
description = 'springboot-server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // 서블릿
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    // 스프링 MVC 추가
    implementation 'org.springframework:spring-webmvc:7.0.8'
}

tasks.named('test') {
    useJUnitPlatform()
}
