spring.application.name=spring-mvc1-2

# ?? ?? ?? ??(?? info. ???? ??? ??? ?? ?? ??)
logging.level.root=info

# hello.springmvc ???? ? ?? ?? ?? ??
# trace > debug > info > warn > error
# trace? ?? ??? ???
#logging.level.hello.springmvc=trace

# debug? trace? ???? ??
# ?? ??? debug ??. ?? ??? info ??
logging.level.hello.springmvc=debug
