# 하나의 파일에서 설정 파일 통합
# 스프링은 설정 데이터 읽을 때 위에서 아래 순서로 읽음 -> 프로필 정보 없어서 기본 정보로 인식이 됨 + 나중에 읽히는 값이 최종 출력 됨
# 프로필을 한 번에 여러 개 활성화할 수도 있다
url=local.db.com
username=local_user
password=local_pw
#---
spring.config.activate.on-profile=dev
url=dev.db.com
username=dev_user
password=dev_pw
#---
spring.config.activate.on-profile=prod
url=prod.db.com
username=prod_user
password=prod_pw
#---
url=hello.db.com
# 프로필이 없어서 기본 설정이든 dev 설정이든 prod 설정이든 url에서는 해당 값이 사용됨